name: Deploy Firebase Hosting

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: docker build -t anti-phishing-app .

      # Extract dist from container
      - name: Extract build
        run: |
          docker create --name temp-container anti-phishing-app
          docker cp temp-container:/output/dist ./app/dist
          docker rm temp-container

      # Install Firebase CLI
      - name: Install Firebase
        run: npm install -g firebase-tools

      # Deploy
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project webapp-98670 --token "${{ secrets.FIREBASE_TOKEN }}"